hash-format = "sha256"

[[files]]
file = "README.md"
hash = "7ddd0533ca3be8713d3cfd915dd5de4aeb9a9cff93662efde0589f63a5f80858"

[[files]]
file = "config/DistantHorizons.toml"
hash = "2ffda846d5231928d176505fac55f356d263abde247a84a91b933d1b789580c2"

[[files]]
file = "config/axesareweapons.json5"
hash = "0abb77ff7bac93972090e77b8171d3f7976c500ed2be4bd946826abd17db200a"

[[files]]
file = "config/collective.json5"
hash = "b6243b955bf123f86c947510d9f8f3a4b5f7b8fe3775d834f458d60a3223847f"

[[files]]
file = "config/farmersdelight-common.json"
hash = "bdd90884cfbde8fad7593b041685789364ac6e6636602550f836e3e03818c2b0"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3cc3011619f098fda6ad213a7c4d1468802ff827591a5917c2b7bf3150bfb2ea"

[[files]]
file = "config/jade/sort-order.json"
hash = "5efe7b1f6c71ba198780ec90a3f2baba727242b75378ba4ddb9fac289c6f983f"

[[files]]
file = "config/justplayerheads.json5"
hash = "f1f888cb5f0da0d8c6dd2aaa866e15f4ceef00528d3602e24a2b7fef7d4b4dd0"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/servercore/config.yml"
hash = "2f87249375833cd75d0975b4f2b85b6ceef5f911ba5e54d1446963bf3f7d4657"

[[files]]
file = "config/servercore/optimizations.yml"
hash = "f6a4950e02e2e2aac4525c924b22500282fc27996d4385de466ab34ff8d6dcd6"

[[files]]
file = "config/sit!/server-config.json"
hash = "557a47e98a398a472750e429aa7433ded5dbda18dd8e38feaa89ef555730850f"

[[files]]
file = "config/sit!/sitting-config.json"
hash = "a8002c8a6799e31f3a911ba332ad954ec235fabcdfa7efb9cb61a73efbc842d5"

[[files]]
file = "config/spark/config.json"
hash = "992ba9f3a4a7ce3de112eb95575328956fdc3ce6781c455ebce7b23db7e7da42"

[[files]]
file = "config/spark/tmp/about.txt"
hash = "8057ccf4540ea269b0fc332225859f44d8f3a55d891fa2e7a3447b6202658d2a"

[[files]]
file = "config/styled-chat.json"
hash = "5e42cec6e3ed64996eced65c11b813286874a6ffed685a0b141171ced6a24335"

[[files]]
file = "config/vcinteraction/vcinteraction.properties"
hash = "b428c07faaed97d3bee29aa748bb8a1773f5145008435c08d9b5aed5151da3ad"

[[files]]
file = "config/voicechat/translations.properties"
hash = "b258a94a5ed60fbf93b66c452c3d6e36b044f630741f90e5b13852a4805b235e"

[[files]]
file = "config/voicechat/voicechat-server.properties"
hash = "1173e615040e7b5d8302da6b3b908432177f38270e9be290726340abf02fe09a"

[[files]]
file = "mods/ACE_mc1.21.11-4.3.jar"
hash = "67afa005b446243ff1eb2dd9dc3b8f3f40c0ee5149be246d8716a467aada5056"

[[files]]
file = "mods/AxesAreWeapons-1.9.5-fabric-1.21.11.jar"
hash = "1547b99c8dc69f3516c840cab135023b861fa4638b9d66e4a7f5c7ee392b2917"

[[files]]
file = "mods/DistantHorizons-2.4.5-b-1.21.11-fabric-neoforge.jar"
hash = "7694c7a17e55f5bef21b456c22a2b1c4e48060b37467dee2b71d4c12e586bc3f"

[[files]]
file = "mods/FABRIC-1.21.11-0.1.jar"
hash = "67a5b5ac1d462750b976ebc860e0224277e26f506f225784008b504bb28102db"

[[files]]
file = "mods/FarmersDelight-1.21.11-3.4.3+refabricated.jar"
hash = "8a4cb5baf569395d1a6e794d477a8b4244bddde2178ea5533d15eb0339cb2ab2"

[[files]]
file = "mods/ForgeConfigAPIPort-v21.11.1-mc1.21.11-Fabric.jar"
hash = "31a0686904fad1cfdeb1d6b011ac1c2280990d6e76ac2416468147e2246b4db1"

[[files]]
file = "mods/InvView-1.4.19-1.21.11+.jar"
hash = "a11820ecbc5be6ba5550141ed7019f1a20ab401214ff056d25691d840dc580bd"

[[files]]
file = "mods/Jade-1.21.11-Fabric-21.1.0.jar"
hash = "a5da2686eea1259b51623dd137b5ec098869d40323fcc526f2a6ed33c937d3bc"

[[files]]
file = "mods/actually-harvest.pw.toml"
hash = "86dbb557dc9483923cc56cb7a049116eb9ec80a307c4ba452d51673619c37ab6"
metafile = true

[[files]]
file = "mods/actuallyharvest-1.21.11-fabric-1.1.7.0-FABRIC.jar"
hash = "93f6e3792d553b53f56da6a9b9e0247e5b98de2919a9b4095e938805a899474c"

[[files]]
file = "mods/appleskin-fabric-mc1.21.11-3.0.7.jar"
hash = "50e8c3eaf69f5919a16cc4228cfabd5f3b9d77413d267834992c3e3c51ae93ed"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "ed50f3b3feba91fa31915aefb40690bc322f37be83490e6b59a443e83a46a542"
metafile = true

[[files]]
file = "mods/audaki-cart-engine.pw.toml"
hash = "42538c5ce50442ed0294ccee2bf1cb619e8590b6bc898fc30eb314b3d281b54d"
metafile = true

[[files]]
file = "mods/audioplayer-fabric-2.1.0+1.21.11.jar"
hash = "2cbbe8ec2bdebd92a81e29cb1c30dc17a75ef1f8fd9cea6fdc661708e274fd21"

[[files]]
file = "mods/audioplayer.pw.toml"
hash = "5f2f0ac0042cf3a274098074d3acee7e61692d1c0a2ef87d883f9607aeefef9d"
metafile = true

[[files]]
file = "mods/axes-are-weapons.pw.toml"
hash = "560e35197f3a2d34b709aeb79098e4ac480b52bf2115aa8f5c5ed194d88b29c9"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "fbb61854650a7cdf7eb2244e0599bae2f0541864a9b7cf74f8272972e6bdb18e"
metafile = true

[[files]]
file = "mods/cloth-config-21.11.153-fabric.jar"
hash = "8a40c84e5ecde525acfb6c4e13b8002dacfca3ef9534d7faf6e8049656f423c8"

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/collective-1.21.11-8.13.jar"
hash = "f79aa00b159be2ca65421557872939d1aa3532f4f91066fa38b8ab9c0265d2ef"

[[files]]
file = "mods/collective.pw.toml"
hash = "c2a61b492dd0d7a156e15b7572adb40552b94c09658cc3c6d7faf99288d094c7"
metafile = true

[[files]]
file = "mods/craft-music-discs-v2.0.0.jar"
hash = "577d5e51495158fac8573b6a267ad851a3f5272318230c7af0735ec6dc04eb83"

[[files]]
file = "mods/craft-music-discs.pw.toml"
hash = "5dc351db5c6c59936d01993c0b706b1e300ecf2512416fff2340f0d0622cd69e"
metafile = true

[[files]]
file = "mods/craftable-name-tag.pw.toml"
hash = "13a527880bac9bd249ce8f63299ae26c8452fe19edbb5f6ee75dc055f398d2fa"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "479cc9008a66ce4dea0b0be0f749a986d73f5fe778516d6682a5202e19706179"
metafile = true

[[files]]
file = "mods/fabric-api-0.141.1+1.21.11.jar"
hash = "6a577f83bd8b33c9404127d16531acc9c4195f47de0395957c9d4cd09d7b98c6"

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "39b4f43a271700276ff1ae632cf05f90b85f79670d955b50ced036e363a0efe9"
metafile = true

[[files]]
file = "mods/fabric-carpet-1.21.11-1.4.194+v251223.jar"
hash = "1b4d66f0332bda5deee08755e493c2d6ac64d64d5285e1134aa03604975c2521"

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "cf5b0a4b5c04a3f75b0824629daba6d26fff2e5bbf5d0a8e3757b2267149e9f0"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/ferritecore-8.0.3-fabric.jar"
hash = "c86eabacdbf063989b2ca812c8e93f556b8feff1c9dfc07caefa1d90a5c7bf35"

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "b22f1d052eee2810fda73d850dd6f425a1214965e03a5a9dada421abfe74603b"
metafile = true

[[files]]
file = "mods/gravestones-1.2.7+1.21.11+B.jar"
hash = "86b7509825a415f6e2541eb3cf94835f6c10b8c4061d1adf92ac96cfa7ab67db"

[[files]]
file = "mods/invisible-frames-mod.pw.toml"
hash = "a32b6a52f95718610b1bbf9e52979f633374faa57b8e068691e21d02ede39c22"
metafile = true

[[files]]
file = "mods/invisibleframes-1.5.0+1.21.6.jar"
hash = "fadaa72dfb0968fd7413e1c56709b4eb7d446927bfadae04f83a29b115b510e5"

[[files]]
file = "mods/invview.pw.toml"
hash = "80bdecdf7911f4b1b6c57d18717d8f435ae237991efdd4c43c50ba6f42bb2139"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "7bed38b83c963cfa00e11054c8324cc95594a00f8613d306bd9cf12b26a34552"
metafile = true

[[files]]
file = "mods/jei-1.21.11-fabric-27.3.0.14.jar"
hash = "64f2ab22a5c66bbcce2c652ebffe561f61162dc13a65f09eed9211b3c8669963"

[[files]]
file = "mods/jei.pw.toml"
hash = "b953bbb028f8c6f1720f9d1c7d6b8bd99fa837a1732006aa8633a3f7537c6f39"
metafile = true

[[files]]
file = "mods/just-player-heads.pw.toml"
hash = "642c233a5f38341db207393f0376f3c6d49f376f398add37553d6ccd9f7a9baa"
metafile = true

[[files]]
file = "mods/justplayerheads-1.21.11-4.3.jar"
hash = "fec21c60974534cda5e6566d0f074e9d253496e0342652f953eb2cff68ccf836"

[[files]]
file = "mods/lithium-fabric-0.21.2+mc1.21.11.jar"
hash = "3106639c73ee23f44bfbe5e5e7a8154dfe3ad0fd48491e4a85767598ed7b0739"

[[files]]
file = "mods/lithium.pw.toml"
hash = "0e87ab10adb3db84b1d6d2ce8bdd7158878b56c965055056b10ad6cde2634568"
metafile = true

[[files]]
file = "mods/more-delight.pw.toml"
hash = "3f0449bb15482e4755703638bb343407accece8208ac6df225623db2852523a1"
metafile = true

[[files]]
file = "mods/moredelight-25.12.10-1.21.11-fabric.jar"
hash = "295cadc0eab2d7976a9e54576c5e6f1b545e508dbb4b4a018fcc10a4c1cc2ce9"

[[files]]
file = "mods/otterlib-0.2.2.1+1.21.11-fabric.jar"
hash = "c3b800cfdf13b23a96241c1852c8406bf50c2158d1607c7a0bb12c2a1bda8ca6"

[[files]]
file = "mods/otterlib.pw.toml"
hash = "a7aaa19d5a9df2b847686f17f8bdd80ded4097a3880fb89a30175a14ae45c5e2"
metafile = true

[[files]]
file = "mods/pneumono_core.pw.toml"
hash = "6a6eb01c3a425f9dd78dcec3337898cc2b1ac8e6e7dec2f209e63b75ae55e7f4"
metafile = true

[[files]]
file = "mods/pneumono_gravestones.pw.toml"
hash = "c34adb8019547bbc68199d19d9963347b75692ca2561cda2ce5562f2566b22f7"
metafile = true

[[files]]
file = "mods/pneumonocore-1.2.1+1.21.11+A.jar"
hash = "288fc06a1a345056fca85d4590dae1d6ebe99252ebad1579bef469bbaa16c59d"

[[files]]
file = "mods/scholar-fabric-1.21.11-1.1.11.jar"
hash = "b45fb7ada4289c25c8f18c3d7ae39fa063e524258119ba45353c7c15332476ac"

[[files]]
file = "mods/scholar.pw.toml"
hash = "ff74081c2823dd62ab228805e2d5830292ffb0febc528df0ac6a483d62d55f31"
metafile = true

[[files]]
file = "mods/servercore-fabric-1.5.15+1.21.11.jar"
hash = "efc7a163f0c539d03c5ec42c092f9be56a0fe8666b871a63082502ef79330510"

[[files]]
file = "mods/servercore.pw.toml"
hash = "16a351dac4db6e5b8035f56090710a227d33482797ef5bcc09a367099304be74"
metafile = true

[[files]]
file = "mods/servux-fabric-1.21.11-0.9.1.jar"
hash = "b2124f6509f0d52bc2bb32cbfe7ffae0372dd6ff2813f16a483ac3c987a636ba"

[[files]]
file = "mods/servux.pw.toml"
hash = "f3b5fd87fcc538dfb46b73005ab3e0c67ce66995c570677f1e46a912f968b671"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "9ff1a261860fcb16a7c7f124d738abcdfc1297363412d237540685003ff04d6b"
metafile = true

[[files]]
file = "mods/sit!-1.2.5.2+1.21.11.jar"
hash = "5f192b572ef959cf4d1d9b7de1b48ffce95f463453d44bfc3745d42704decebb"

[[files]]
file = "mods/sit!.pw.toml"
hash = "aa2f75744edd5dd05766f39f045e967327afb1d9aa076947030929f29edcc0c2"
metafile = true

[[files]]
file = "mods/spark-1.10.156-fabric.jar"
hash = "36ed138ffde2a2f1fcb32ecbcc7fa21beaf1611e003d19e3ad40954873e572fa"

[[files]]
file = "mods/spark.pw.toml"
hash = "c073f13897a838e3c409e46b8a1d8cb510d6a6584dd815aeadaf4886f1779513"
metafile = true

[[files]]
file = "mods/styled-chat-2.11.0+1.21.11.jar"
hash = "1000d14ba1952db4ed395b781a0892ae90c3103849e8e42229279f6c08eeaeba"

[[files]]
file = "mods/styled-chat.pw.toml"
hash = "d339c1243682f47b0500ed2cb7334af2114c76ec8ea2f64d1c261ff75324775b"
metafile = true

[[files]]
file = "mods/vcinteraction-fabric-1.21.11-1.0.8.jar"
hash = "7aadd28fd8f2160bdf91b64416a45830219252a6d051a427f29e5a121ae3bd25"

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
hash = "ee63322f2464e89370cf12c55740929876bf4591ab17b1ff4204d331c5cd272f"
metafile = true

[[files]]
file = "mods/voicechat-fabric-1.21.11-2.6.11.jar"
hash = "1b5fe15fee0655ead032762b95a35d07cbbe0dfd21c25ee0b5247ac9d1b9353b"

[[files]]
file = "mods/xaerominimap-fabric-1.21.11-25.3.5.jar"
hash = "7658b6026fa5df2c3dacfdcd2951e156c75fbc5acea846e0639147b8f4236b52"

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "2c6ad75996654f04dfe44a15d64abd5c2ae1d9fddca6d3e24cab236f3d589195"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "e9395a06548b7cedb1d8df2a80569b858ea4ffe49d8cb31fdc363328658319f3"
metafile = true

[[files]]
file = "mods/xaeroworldmap-fabric-1.21.11-1.40.6.jar"
hash = "c3896b938d6d1af796a3ff96135c63a610a34adc263ec6900ad8b039432a2d3b"

[[files]]
file = "packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"

[[files]]
file = "packwiz-installer.jar"
hash = "c9f646908d340d84773948a9a7d98bc1dae250d35e1016dc6e2b8459760b5598"

[[files]]
file = "packwiz.json"
hash = "ea51db5d6d6f00b9aab544af20cfe347c8dcc18a56cbc21894774406c103ca6e"
