hash-format = "sha256"

[[files]]
file = "README.md"
hash = "b0004935c5e8f7ff3a9f4cb1cd8e0419ecb16ea7efb009ec8a2e470670301aad"

[[files]]
file = "config/DistantHorizons.toml"
hash = "2ffda846d5231928d176505fac55f356d263abde247a84a91b933d1b789580c2"

[[files]]
file = "config/axesareweapons.json5"
hash = "0abb77ff7bac93972090e77b8171d3f7976c500ed2be4bd946826abd17db200a"

[[files]]
file = "config/collective.json5"
hash = "b6243b955bf123f86c947510d9f8f3a4b5f7b8fe3775d834f458d60a3223847f"

[[files]]
file = "config/farmersdelight-common.json"
hash = "bdd90884cfbde8fad7593b041685789364ac6e6636602550f836e3e03818c2b0"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3cc3011619f098fda6ad213a7c4d1468802ff827591a5917c2b7bf3150bfb2ea"

[[files]]
file = "config/jade/sort-order.json"
hash = "5efe7b1f6c71ba198780ec90a3f2baba727242b75378ba4ddb9fac289c6f983f"

[[files]]
file = "config/justplayerheads.json5"
hash = "f1f888cb5f0da0d8c6dd2aaa866e15f4ceef00528d3602e24a2b7fef7d4b4dd0"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/servercore/config.yml"
hash = "2f87249375833cd75d0975b4f2b85b6ceef5f911ba5e54d1446963bf3f7d4657"

[[files]]
file = "config/servercore/optimizations.yml"
hash = "f6a4950e02e2e2aac4525c924b22500282fc27996d4385de466ab34ff8d6dcd6"

[[files]]
file = "config/sit!/server-config.json"
hash = "557a47e98a398a472750e429aa7433ded5dbda18dd8e38feaa89ef555730850f"

[[files]]
file = "config/sit!/sitting-config.json"
hash = "a8002c8a6799e31f3a911ba332ad954ec235fabcdfa7efb9cb61a73efbc842d5"

[[files]]
file = "config/spark/config.json"
hash = "992ba9f3a4a7ce3de112eb95575328956fdc3ce6781c455ebce7b23db7e7da42"

[[files]]
file = "config/spark/tmp/about.txt"
hash = "8057ccf4540ea269b0fc332225859f44d8f3a55d891fa2e7a3447b6202658d2a"

[[files]]
file = "config/styled-chat.json"
hash = "5e42cec6e3ed64996eced65c11b813286874a6ffed685a0b141171ced6a24335"

[[files]]
file = "config/vcinteraction/vcinteraction.properties"
hash = "b428c07faaed97d3bee29aa748bb8a1773f5145008435c08d9b5aed5151da3ad"

[[files]]
file = "config/voicechat/translations.properties"
hash = "b258a94a5ed60fbf93b66c452c3d6e36b044f630741f90e5b13852a4805b235e"

[[files]]
file = "config/voicechat/voicechat-server.properties"
hash = "1173e615040e7b5d8302da6b3b908432177f38270e9be290726340abf02fe09a"

[[files]]
file = "mods/audaki-cart-engine.pw.toml"
hash = "42538c5ce50442ed0294ccee2bf1cb619e8590b6bc898fc30eb314b3d281b54d"
metafile = true

[[files]]
file = "mods/axes-are-weapons.pw.toml"
hash = "560e35197f3a2d34b709aeb79098e4ac480b52bf2115aa8f5c5ed194d88b29c9"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "72f3dbfcfbf16d8437d865b090c4338cf32de86f290e8e8dde5626cb301bb4c7"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "c2a61b492dd0d7a156e15b7572adb40552b94c09658cc3c6d7faf99288d094c7"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "8395078cc9b359cf76e0bf950c57b886101446d1c7893a733c9cc16fd6c7d2f8"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cf6edd71a012b437bca4bcac93c44d1109632db31b5f638d28b58fa77cf771b5"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "3403d9412dbde3e26f7a94b140f58c37757224485bc3962a3917a47d7f904d34"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/invisible-frames-mod.pw.toml"
hash = "a32b6a52f95718610b1bbf9e52979f633374faa57b8e068691e21d02ede39c22"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "53ca4dd806e6ae6b3d72d7707ff59c30bb6b07b7f9c2b0a2a82534c0ecfb78c4"
metafile = true

[[files]]
file = "mods/just-player-heads.pw.toml"
hash = "642c233a5f38341db207393f0376f3c6d49f376f398add37553d6ccd9f7a9baa"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "88a36b21d538d44aca7dd0a7e5ad8c09b1b263be3f4381e3bb22bc9f94ee7290"
metafile = true

[[files]]
file = "mods/more-delight.pw.toml"
hash = "3f0449bb15482e4755703638bb343407accece8208ac6df225623db2852523a1"
metafile = true

[[files]]
file = "mods/otterlib.pw.toml"
hash = "a7aaa19d5a9df2b847686f17f8bdd80ded4097a3880fb89a30175a14ae45c5e2"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "16a351dac4db6e5b8035f56090710a227d33482797ef5bcc09a367099304be74"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "0a76421b847a5f403a4b9fc1f211a9792564c2a4c238cd7fd92727f560dc9f9a"
metafile = true

[[files]]
file = "mods/sit!.pw.toml"
hash = "339a5093dea358ed558e77484dff1d4ac0665883857f087478c49279a893e02b"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c073f13897a838e3c409e46b8a1d8cb510d6a6584dd815aeadaf4886f1779513"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
hash = "d339c1243682f47b0500ed2cb7334af2114c76ec8ea2f64d1c261ff75324775b"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
hash = "ee63322f2464e89370cf12c55740929876bf4591ab17b1ff4204d331c5cd272f"
metafile = true
