name = "Server Mods"
author = "DelicateChaos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3fffff1a670f3d46058a3fa3ceb2127ac3b9792e0ce4e446abd859dcd60a9da"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
