name = "Server Mods"
author = "DelicateChaos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "880826b8c77bad62a029359ac5f1e4732607b1c5293a2a2e38ee7c0b56316ac2"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
