name = "Server Mods"
author = "DelicateChaos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59655752b449af3460fb899d71c4d507cd33a62d807bb429991efd9beb938793"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
